# Generated by Django 5.2 on 2026-08-16 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='category',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='food_name',
            new_name='food_item',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='available_until',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='prepared_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
