# Generated by Django 5.2 on 2026-08-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_remove_donation_claimed_by_remove_donation_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
